/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packcorridinha;

/**
 *
 * @author gabri
 */
public class Agrvai extends javax.swing.JFrame {

    /**
     * Creates new form Agrvai
     */
    public Agrvai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPink = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrinho-rosa.png"))); // NOI18N
        lblPink.setText("jLabel1");
        getContentPane().add(lblPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 82, -1));

        lblRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrinho.png"))); // NOI18N
        lblRed.setText("jLabel1");
        getContentPane().add(lblRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 84, -1));

        lblPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pista.png"))); // NOI18N
        getContentPane().add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
        int xR = lblRed.getX();
        int yR = lblRed.getY();
        
        if(evt.getKeyCode() == evt.VK_UP){
            lblRed.setLocation(xR, yR - 5);
         }
        if(evt.getKeyCode() == evt.VK_DOWN){
            lblRed.setLocation(xR, yR - 10);
         }
        
        int xP = lblPink.getX();
        int yP = lblPink.getY();
        
         if(evt.getKeyCode() == evt.VK_W){
            lblPink.setLocation(xP, yP - 5);
         }
        if(evt.getKeyCode() == evt.VK_S){
            lblPink.setLocation(xP, yP - 10);
         }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agrvai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPink;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblRed;
    // End of variables declaration//GEN-END:variables
}
