/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packcorridinha;

import java.awt.Color;
import static java.lang.Thread.sleep;
import javax.naming.ldap.Rdn;

/**
 *
 * @author gabri
 */
public class Agrvai extends javax.swing.JFrame {

    int miliseg = 0;
    int seg = 0;
    boolean estado = true;
    int numeroSupremo =0;
    
    int redn;
    int pinkn;
    
   
    
    public Agrvai() {
        initComponents();
        painelConometro.setVisible(false);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPink = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblSetaCima = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        painelConometro = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblVencedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrinho-rosa.png"))); // NOI18N
        lblPink.setText("jLabel1");
        getContentPane().add(lblPink, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 82, -1));

        lblRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrinho.png"))); // NOI18N
        lblRed.setText("jLabel1");
        getContentPane().add(lblRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 84, -1));

        lblSetaCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecla-seta-cima.png"))); // NOI18N
        getContentPane().add(lblSetaCima, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tecla-w.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        painelConometro.setOpaque(false);
        painelConometro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Restart");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelConometro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

        lblVencedor.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lblVencedor.setForeground(new java.awt.Color(255, 0, 0));
        lblVencedor.setText("car");
        painelConometro.add(lblVencedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, 150, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("WIN");
        painelConometro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bandeira-cronometro.png"))); // NOI18N
        painelConometro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(painelConometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 170));

        lblPista.setBackground(new java.awt.Color(255, 255, 255));
        lblPista.setForeground(new java.awt.Color(255, 255, 255));
        lblPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pista.png"))); // NOI18N
        getContentPane().add(lblPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
         
        int xR = lblRed.getX();
        int yR = lblRed.getY();
        
        if(evt.getKeyCode() == evt.VK_UP){
            lblRed.setLocation(xR, yR - 5);
            redn++;
         }
       
           if(redn == 106){
           lblVencedor.setText(" Red");
           lblVencedor.setForeground(Color.red);
           painelConometro.setVisible(true);
           }
         
        
        int xP = lblPink.getX();
        int yP = lblPink.getY();
        
         if(evt.getKeyCode() == evt.VK_W){
            lblPink.setLocation(xP, yP - 5);
            pinkn++;
         }
         if(pinkn == 106){
           lblVencedor.setText("Pink");
           lblVencedor.setForeground(Color.pink);
           painelConometro.setVisible(true);         }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agrvai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agrvai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPink;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblSetaCima;
    private javax.swing.JLabel lblVencedor;
    private javax.swing.JPanel painelConometro;
    // End of variables declaration//GEN-END:variables
}
