/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packcorridinha;

import static java.lang.Thread.sleep;

/**
 *
 * @author gabri
 */
public class CronometroJanela extends javax.swing.JFrame {
    int miliseg = 0;
    int seg = 0;
    boolean estado = true;
    
    public CronometroJanela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConometro = new javax.swing.JPanel();
        lblNum = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelConometro.setOpaque(false);
        painelConometro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNum.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lblNum.setForeground(new java.awt.Color(255, 0, 0));
        lblNum.setText("0");
        painelConometro.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bandeira-cronometro.png"))); // NOI18N
        painelConometro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("START");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelConometro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, -1));

        getContentPane().add(painelConometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 160));

        setSize(new java.awt.Dimension(205, 160));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // começar a corrida
              estado = true;
        Thread hilo = new Thread(){
        public void run(){
        for(;;){
        if(seg < 4){
            try {
                sleep(1);
                if(miliseg>=700){
                miliseg = 0;
                seg++;
                }
                lblNum.setText(Integer.toString(seg));
                
                miliseg++;
            } catch (Exception e) {
            }
        }else{
            painelConometro.setVisible(false);
            Agrvai objAgrvai = new Agrvai();          
            objAgrvai.numeroSupremo=3;
            dispose();
           
        break;}
        }
        }
        };
        hilo.start();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CronometroJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CronometroJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CronometroJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CronometroJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CronometroJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNum;
    private javax.swing.JPanel painelConometro;
    // End of variables declaration//GEN-END:variables
}
